%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/pbebbo/github/QMUL-Matlab/Session 3/FTSE.csv
%
% Auto-generated by MATLAB on 19-Feb-2022 11:59:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Open", "High", "Low", "Close", "Volume", "AdjClose"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd");

% Import the data
tbl = readtable("/home/pbebbo/github/QMUL-Matlab/Session 3/FTSE.csv", opts);

%% Convert to output type
Date = tbl.Date;
Open = tbl.Open;
High = tbl.High;
Low = tbl.Low;
Close = tbl.Close;
Volume = tbl.Volume;
AdjClose = tbl.AdjClose;

%% Clear temporary variables
clear opts tbl